"""empty message

Revision ID: 712f947a8693
Revises: 
Create Date: 2021-01-23 11:53:14.667341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '712f947a8693'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.drop_column('movies', 'releasedate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('releasedate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###
